// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBteNw3e9VKWoxajaqamiQqWx4ihrT7DjA',
    appId: '1:1085838500345:web:b322a76ecda0ef1f45dd28',
    messagingSenderId: '1085838500345',
    projectId: 'letspadel-38070',
    authDomain: 'letspadel-38070.firebaseapp.com',
    storageBucket: 'letspadel-38070.appspot.com',
    measurementId: 'G-0YQJ1M8KJH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL6l69k8LRkatQu0O2rBysL0Hahw5Zp7s',
    appId: '1:1085838500345:ios:d34aa66c2ce5a72a45dd28',
    messagingSenderId: '1085838500345',
    projectId: 'letspadel-38070',
    storageBucket: 'letspadel-38070.appspot.com',
    iosBundleId: 'com.project.padel',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL6l69k8LRkatQu0O2rBysL0Hahw5Zp7s',
    appId: '1:1085838500345:ios:d34aa66c2ce5a72a45dd28',
    messagingSenderId: '1085838500345',
    projectId: 'letspadel-38070',
    storageBucket: 'letspadel-38070.appspot.com',
    iosBundleId: 'com.project.padel',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkFnmiqZmd4Dtzf2dEfHg4vnXsDxmCYUI',
    appId: '1:1085838500345:android:0ceb45694fdce06845dd28',
    messagingSenderId: '1085838500345',
    projectId: 'letspadel-38070',
    storageBucket: 'letspadel-38070.appspot.com',
  );

}